// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";

// import Header from "@/components/header";
// import { Toaster } from "sonner";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Spendly- track your expenses",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={`${inter.className}`}>
//           {/*header */}
//           <Header />
//           <main className="min-h-screen  ">{children}</main>
//           <Toaster richColors/>
//           {/*footer*/}
//           <footer className="bg-blue-50  py-10 ">
//             <div className="container mx-auto px-4 text-center text-grey-600">
//               <p>© 2025 Spendly. All rights reserved.</p>
//             </div>
//           </footer>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import Header from "@/components/header";
import { Toaster } from "sonner";
import Footer from "@/components/footer"; // 👈 Import your new footer here

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spendly — Track Your Expenses",
  description:
    "Track your expenses, set budgets, and manage your money easily with Spendly.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} flex flex-col min-h-screen`}>
          {/* Header */}
          <Header />

          {/* Main content */}
          <main className="flex-1">{children}</main>

          {/* Toaster Notifications */}
          <Toaster richColors position="top-right" />

          {/* Footer (modern version) */}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
